# Generated by Django 3.2.12 on 2022-02-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('abbreviation', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=11)),
                ('elevation', models.DecimalField(decimal_places=2, max_digits=6)),
                ('public_IP', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('Material', models.CharField(max_length=20)),
                ('geology', models.CharField(max_length=20)),
                ('basement', models.DecimalField(decimal_places=0, max_digits=6)),
                ('floor_above_ground', models.DecimalField(decimal_places=0, max_digits=6)),
                ('total_height', models.DecimalField(decimal_places=1, max_digits=6)),
                ('outlook', models.CharField(max_length=20)),
                ('section_view', models.CharField(max_length=20)),
                ('building_date', models.CharField(max_length=20)),
                ('substantial_completion_date', models.CharField(max_length=20)),
                ('activation_date', models.CharField(max_length=20)),
                ('contact_person', models.CharField(max_length=20)),
                ('remark', models.CharField(max_length=20)),
            ],
        ),
    ]
